# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xepmts
from api.pmt_dcr_api import PmtDcrApi  # noqa: E501
from xepmts.rest import ApiException


class TestPmtDcrApi(unittest.TestCase):
    """PmtDcrApi unit test stubs"""

    def setUp(self):
        self.api = api.pmt_dcr_api.PmtDcrApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deletepmt_dcr_item(self):
        """Test case for deletepmt_dcr_item

        Deletes a pmt_dcr document  # noqa: E501
        """
        pass

    def test_deletepmt_dcrs(self):
        """Test case for deletepmt_dcrs

        Deletes all pmt_dcrs  # noqa: E501
        """
        pass

    def test_getpmt_dcr_item(self):
        """Test case for getpmt_dcr_item

        Retrieves a pmt_dcr document  # noqa: E501
        """
        pass

    def test_getpmt_dcrs(self):
        """Test case for getpmt_dcrs

        Retrieves one or more pmt_dcrs  # noqa: E501
        """
        pass

    def test_postpmt_dcrs(self):
        """Test case for postpmt_dcrs

        Stores one or more pmt_dcrs.  # noqa: E501
        """
        pass

    def test_putpmt_dcr_item(self):
        """Test case for putpmt_dcr_item

        Replaces a pmt_dcr document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
