# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xepmts
from models.pmt_dcr import PmtDcr  # noqa: E501
from xepmts.rest import ApiException


class TestPmtDcr(unittest.TestCase):
    """PmtDcr unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPmtDcr(self):
        """Test PmtDcr"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xepmts.models.pmt_dcr.PmtDcr()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
