# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pmtdb_client
from api.pmt_afterpulse_api import PmtAfterpulseApi  # noqa: E501
from pmtdb_client.rest import ApiException


class TestPmtAfterpulseApi(unittest.TestCase):
    """PmtAfterpulseApi unit test stubs"""

    def setUp(self):
        self.api = api.pmt_afterpulse_api.PmtAfterpulseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deletepmt_afterpulse_item(self):
        """Test case for deletepmt_afterpulse_item

        Deletes a pmt_afterpulse document  # noqa: E501
        """
        pass

    def test_deletepmt_afterpulses(self):
        """Test case for deletepmt_afterpulses

        Deletes all pmt_afterpulses  # noqa: E501
        """
        pass

    def test_getpmt_afterpulse_item(self):
        """Test case for getpmt_afterpulse_item

        Retrieves a pmt_afterpulse document  # noqa: E501
        """
        pass

    def test_getpmt_afterpulses(self):
        """Test case for getpmt_afterpulses

        Retrieves one or more pmt_afterpulses  # noqa: E501
        """
        pass

    def test_postpmt_afterpulses(self):
        """Test case for postpmt_afterpulses

        Stores one or more pmt_afterpulses.  # noqa: E501
        """
        pass

    def test_putpmt_afterpulse_item(self):
        """Test case for putpmt_afterpulse_item

        Replaces a pmt_afterpulse document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
