# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xepmts
from api.nveto_pmt_mapping_api import NvetoPmtMappingApi  # noqa: E501
from xepmts.rest import ApiException


class TestNvetoPmtMappingApi(unittest.TestCase):
    """NvetoPmtMappingApi unit test stubs"""

    def setUp(self):
        self.api = api.nveto_pmt_mapping_api.NvetoPmtMappingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deletenveto_pmt_mapping_item(self):
        """Test case for deletenveto_pmt_mapping_item

        Deletes a nveto_pmt_mapping document  # noqa: E501
        """
        pass

    def test_deletenveto_pmt_mappings(self):
        """Test case for deletenveto_pmt_mappings

        Deletes all nveto_pmt_mappings  # noqa: E501
        """
        pass

    def test_getnveto_pmt_mapping_item(self):
        """Test case for getnveto_pmt_mapping_item

        Retrieves a nveto_pmt_mapping document  # noqa: E501
        """
        pass

    def test_getnveto_pmt_mappings(self):
        """Test case for getnveto_pmt_mappings

        Retrieves one or more nveto_pmt_mappings  # noqa: E501
        """
        pass

    def test_postnveto_pmt_mappings(self):
        """Test case for postnveto_pmt_mappings

        Stores one or more nveto_pmt_mappings.  # noqa: E501
        """
        pass

    def test_putnveto_pmt_mapping_item(self):
        """Test case for putnveto_pmt_mapping_item

        Replaces a nveto_pmt_mapping document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
