# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pmtdb_client
from api.voltage_map_api import VoltageMapApi  # noqa: E501
from pmtdb_client.rest import ApiException


class TestVoltageMapApi(unittest.TestCase):
    """VoltageMapApi unit test stubs"""

    def setUp(self):
        self.api = api.voltage_map_api.VoltageMapApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deletevoltage_map_item(self):
        """Test case for deletevoltage_map_item

        Deletes a voltage_map document  # noqa: E501
        """
        pass

    def test_deletevoltage_maps(self):
        """Test case for deletevoltage_maps

        Deletes all voltage_maps  # noqa: E501
        """
        pass

    def test_getvoltage_map_item(self):
        """Test case for getvoltage_map_item

        Retrieves a voltage_map document  # noqa: E501
        """
        pass

    def test_getvoltage_map_item_by_name(self):
        """Test case for getvoltage_map_item_by_name

        Retrieves a voltage_map document by name  # noqa: E501
        """
        pass

    def test_getvoltage_maps(self):
        """Test case for getvoltage_maps

        Retrieves one or more voltage_maps  # noqa: E501
        """
        pass

    def test_postvoltage_maps(self):
        """Test case for postvoltage_maps

        Stores one or more voltage_maps.  # noqa: E501
        """
        pass

    def test_putvoltage_map_item(self):
        """Test case for putvoltage_map_item

        Replaces a voltage_map document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
