# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pmtdb_client
from api.pmt_install_api import PmtInstallApi  # noqa: E501
from pmtdb_client.rest import ApiException


class TestPmtInstallApi(unittest.TestCase):
    """PmtInstallApi unit test stubs"""

    def setUp(self):
        self.api = api.pmt_install_api.PmtInstallApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deletepmt_install_item(self):
        """Test case for deletepmt_install_item

        Deletes a pmt_install document  # noqa: E501
        """
        pass

    def test_deletepmt_installs(self):
        """Test case for deletepmt_installs

        Deletes all pmt_installs  # noqa: E501
        """
        pass

    def test_getpmt_install_item(self):
        """Test case for getpmt_install_item

        Retrieves a pmt_install document  # noqa: E501
        """
        pass

    def test_getpmt_install_item_by_pmt_no(self):
        """Test case for getpmt_install_item_by_pmt_no

        Retrieves a pmt_install document by pmt_no  # noqa: E501
        """
        pass

    def test_getpmt_installs(self):
        """Test case for getpmt_installs

        Retrieves one or more pmt_installs  # noqa: E501
        """
        pass

    def test_postpmt_installs(self):
        """Test case for postpmt_installs

        Stores one or more pmt_installs.  # noqa: E501
        """
        pass

    def test_putpmt_install_item(self):
        """Test case for putpmt_install_item

        Replaces a pmt_install document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
