# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pmtdb_client
from models.datasheet import Datasheet  # noqa: E501
from pmtdb_client.rest import ApiException


class TestDatasheet(unittest.TestCase):
    """Datasheet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDatasheet(self):
        """Test Datasheet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pmtdb_client.models.datasheet.Datasheet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
