# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xepmts
from models.pmt_gain import PmtGain  # noqa: E501
from xepmts.rest import ApiException


class TestPmtGain(unittest.TestCase):
    """PmtGain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPmtGain(self):
        """Test PmtGain"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xepmts.models.pmt_gain.PmtGain()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
