# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PmtDcr(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pmt_no': 'int',
        'dcr_mean': 'float',
        'dcr_std_dev': 'float',
        'run': 'int',
        'id': 'str'
    }

    attribute_map = {
        'pmt_no': 'pmt_no',
        'dcr_mean': 'dcr_mean',
        'dcr_std_dev': 'dcr_std_dev',
        'run': 'run',
        'id': '_id'
    }

    def __init__(self, pmt_no=None, dcr_mean=None, dcr_std_dev=None, run=None, id=None):  # noqa: E501
        """PmtDcr - a model defined in Swagger"""  # noqa: E501
        self._pmt_no = None
        self._dcr_mean = None
        self._dcr_std_dev = None
        self._run = None
        self._id = None
        self.discriminator = None
        if pmt_no is not None:
            self.pmt_no = pmt_no
        if dcr_mean is not None:
            self.dcr_mean = dcr_mean
        if dcr_std_dev is not None:
            self.dcr_std_dev = dcr_std_dev
        if run is not None:
            self.run = run
        if id is not None:
            self.id = id

    @property
    def pmt_no(self):
        """Gets the pmt_no of this PmtDcr.  # noqa: E501


        :return: The pmt_no of this PmtDcr.  # noqa: E501
        :rtype: int
        """
        return self._pmt_no

    @pmt_no.setter
    def pmt_no(self, pmt_no):
        """Sets the pmt_no of this PmtDcr.


        :param pmt_no: The pmt_no of this PmtDcr.  # noqa: E501
        :type: int
        """

        self._pmt_no = pmt_no

    @property
    def dcr_mean(self):
        """Gets the dcr_mean of this PmtDcr.  # noqa: E501


        :return: The dcr_mean of this PmtDcr.  # noqa: E501
        :rtype: float
        """
        return self._dcr_mean

    @dcr_mean.setter
    def dcr_mean(self, dcr_mean):
        """Sets the dcr_mean of this PmtDcr.


        :param dcr_mean: The dcr_mean of this PmtDcr.  # noqa: E501
        :type: float
        """

        self._dcr_mean = dcr_mean

    @property
    def dcr_std_dev(self):
        """Gets the dcr_std_dev of this PmtDcr.  # noqa: E501


        :return: The dcr_std_dev of this PmtDcr.  # noqa: E501
        :rtype: float
        """
        return self._dcr_std_dev

    @dcr_std_dev.setter
    def dcr_std_dev(self, dcr_std_dev):
        """Sets the dcr_std_dev of this PmtDcr.


        :param dcr_std_dev: The dcr_std_dev of this PmtDcr.  # noqa: E501
        :type: float
        """

        self._dcr_std_dev = dcr_std_dev

    @property
    def run(self):
        """Gets the run of this PmtDcr.  # noqa: E501


        :return: The run of this PmtDcr.  # noqa: E501
        :rtype: int
        """
        return self._run

    @run.setter
    def run(self, run):
        """Sets the run of this PmtDcr.


        :param run: The run of this PmtDcr.  # noqa: E501
        :type: int
        """

        self._run = run

    @property
    def id(self):
        """Gets the id of this PmtDcr.  # noqa: E501


        :return: The id of this PmtDcr.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PmtDcr.


        :param id: The id of this PmtDcr.  # noqa: E501
        :type: str
        """

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PmtDcr, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PmtDcr):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
