# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Datasheet(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pmt_no': 'int',
        'source': 'str',
        'link': 'str',
        'id': 'str'
    }

    attribute_map = {
        'pmt_no': 'pmt_no',
        'source': 'source',
        'link': 'link',
        'id': '_id'
    }

    def __init__(self, pmt_no=None, source=None, link=None, id=None):  # noqa: E501
        """Datasheet - a model defined in Swagger"""  # noqa: E501
        self._pmt_no = None
        self._source = None
        self._link = None
        self._id = None
        self.discriminator = None
        self.pmt_no = pmt_no
        if source is not None:
            self.source = source
        if link is not None:
            self.link = link
        if id is not None:
            self.id = id

    @property
    def pmt_no(self):
        """Gets the pmt_no of this Datasheet.  # noqa: E501


        :return: The pmt_no of this Datasheet.  # noqa: E501
        :rtype: int
        """
        return self._pmt_no

    @pmt_no.setter
    def pmt_no(self, pmt_no):
        """Sets the pmt_no of this Datasheet.


        :param pmt_no: The pmt_no of this Datasheet.  # noqa: E501
        :type: int
        """
        if pmt_no is None:
            raise ValueError("Invalid value for `pmt_no`, must not be `None`")  # noqa: E501

        self._pmt_no = pmt_no

    @property
    def source(self):
        """Gets the source of this Datasheet.  # noqa: E501


        :return: The source of this Datasheet.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this Datasheet.


        :param source: The source of this Datasheet.  # noqa: E501
        :type: str
        """

        self._source = source

    @property
    def link(self):
        """Gets the link of this Datasheet.  # noqa: E501


        :return: The link of this Datasheet.  # noqa: E501
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this Datasheet.


        :param link: The link of this Datasheet.  # noqa: E501
        :type: str
        """

        self._link = link

    @property
    def id(self):
        """Gets the id of this Datasheet.  # noqa: E501


        :return: The id of this Datasheet.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Datasheet.


        :param id: The id of this Datasheet.  # noqa: E501
        :type: str
        """

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Datasheet, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Datasheet):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
